[/Script/Engine.RendererSettings]
; Disabling distance fields avoids requiring a full depth pre-pass, which is slow on standalone XR devices.
r.DistanceFields=0

; This reverts the mobile deferred renderer to single-pass/subpass rendering, which was the default before UE 5.7.
; Multi-pass deferred is currently disabled for VR Template due to rendering issues with mobile multi-view.
r.Mobile.AllowFramebufferFetch=1

; PSO precaching is extremely slow on first launch for standlone XR devices.
; Projects are recommended to use Bundled PSO Caches to avoid stuttering.
; Alternatively, re-enable PSO precaching and conceal it with a loading screen by querying FShaderPipelineCache::NumPrecompilesRemaining().
r.PSOPrecaching=0