// Copyright PICO Technology Co., Ltd. All rights reserved.
// This plugin incorporates portions of the Unreal® Engine. Unreal® is a trademark or registered trademark of Epic Games, Inc. in the United States of America and elsewhere.
// Copyright Epic Games, Inc. All Rights Reserved.

#include "/Engine/Private/Common.ush"

void MainVertexShader(
	float4 InPosition : ATTRIBUTE0,
	float2 InUV : ATTRIBUTE1,
	out float2 OutUV : TEXCOORD0,
	out float4 OutPosition : SV_POSITION
	)
{
	OutPosition = InPosition;
	OutUV = InUV;
}

Texture2D<uint> TextureParameter;
 
void MainWhiteShader(
	out float4 OutColor : SV_Target0
	)
{
	OutColor = float4(1, 1, 1, 1);
}

void MainBlackShader(
	out float4 OutColor : SV_Target0
	)
{
	OutColor = float4(0, 0, 0, 0);
}

Texture2D InTexture;
TextureCube InTextureCube;
SamplerState InTextureSampler;

void MainAlphaInverseShader(
	in float2 uv : TEXCOORD0,
	out float4 OutColor : SV_Target0
	)
{
	float InverseAlpha = 1 - Texture2DSample(InTexture, InTextureSampler, uv).a;
	OutColor = float4(0, 0, 0, InverseAlpha);
}

int CubeFaceIndex;

void MainForCubemap(
	FScreenVertexOutput Input,
	out float4 OutColor : SV_Target0
	)
{
	float u = Input.UV.x * 2. - 1.0;
	float v = Input.UV.y * 2. - 1.0;

	if(CubeFaceIndex == 0)//left
	{
		OutColor = TextureCubeSample(InTextureCube, InTextureSampler, float3(1., v, u));
	}
	else if(CubeFaceIndex == 1)//right
	{
		OutColor = TextureCubeSample(InTextureCube, InTextureSampler, float3(-1., -v, u));
	}
	else if(CubeFaceIndex == 2) //top
	{
		OutColor = TextureCubeSample(InTextureCube, InTextureSampler, float3(-v, 1., u));
	}
	else if(CubeFaceIndex == 3) //bottom
	{
		OutColor = TextureCubeSample(InTextureCube, InTextureSampler, float3(-v, -1., -u));
	}
	else if(CubeFaceIndex == 5)//back
	{
		OutColor = TextureCubeSample(InTextureCube, InTextureSampler, float3(v, u, 1.));
	}
	else if(CubeFaceIndex == 4) //front
	{
		OutColor = TextureCubeSample(InTextureCube, InTextureSampler, float3(v, -u, -1.));
	}
}